//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockifyWeb.EmpresaWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.stockify.pucp.edu.pe/", ConfigurationName="StockifyWeb.EmpresaWS.EmpresaWS")]
    public interface EmpresaWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.stockify.pucp.edu.pe/EmpresaWS/listarEmpresasRequest", ReplyAction="http://services.stockify.pucp.edu.pe/EmpresaWS/listarEmpresasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StockifyWeb.EmpresaWS.listarEmpresasResponse> listarEmpresasAsync(StockifyWeb.EmpresaWS.listarEmpresasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.stockify.pucp.edu.pe/EmpresaWS/obtenerEmpresaRequest", ReplyAction="http://services.stockify.pucp.edu.pe/EmpresaWS/obtenerEmpresaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StockifyWeb.EmpresaWS.obtenerEmpresaResponse> obtenerEmpresaAsync(StockifyWeb.EmpresaWS.obtenerEmpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.stockify.pucp.edu.pe/EmpresaWS/guardarEmpresaRequest", ReplyAction="http://services.stockify.pucp.edu.pe/EmpresaWS/guardarEmpresaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StockifyWeb.EmpresaWS.guardarEmpresaResponse> guardarEmpresaAsync(StockifyWeb.EmpresaWS.guardarEmpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.stockify.pucp.edu.pe/EmpresaWS/eliminarEmpresaRequest", ReplyAction="http://services.stockify.pucp.edu.pe/EmpresaWS/eliminarEmpresaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<StockifyWeb.EmpresaWS.eliminarEmpresaResponse> eliminarEmpresaAsync(StockifyWeb.EmpresaWS.eliminarEmpresaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.stockify.pucp.edu.pe/")]
    public partial class empresa
    {
        
        private bool activoField;
        
        private string emailField;
        
        private int idEmpresaField;
        
        private string razonSocialField;
        
        private string telefonoField;
        
        private tipoDocumento tipoDocumentoField;
        
        private bool tipoDocumentoFieldSpecified;
        
        private tipoEmpresa tipoEmpresaField;
        
        private bool tipoEmpresaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo
        {
            get
            {
                return this.activoField;
            }
            set
            {
                this.activoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idEmpresa
        {
            get
            {
                return this.idEmpresaField;
            }
            set
            {
                this.idEmpresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string razonSocial
        {
            get
            {
                return this.razonSocialField;
            }
            set
            {
                this.razonSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoDocumento tipoDocumento
        {
            get
            {
                return this.tipoDocumentoField;
            }
            set
            {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoDocumentoSpecified
        {
            get
            {
                return this.tipoDocumentoFieldSpecified;
            }
            set
            {
                this.tipoDocumentoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public tipoEmpresa tipoEmpresa
        {
            get
            {
                return this.tipoEmpresaField;
            }
            set
            {
                this.tipoEmpresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoEmpresaSpecified
        {
            get
            {
                return this.tipoEmpresaFieldSpecified;
            }
            set
            {
                this.tipoEmpresaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.stockify.pucp.edu.pe/")]
    public enum tipoDocumento
    {
        
        /// <remarks/>
        DNI,
        
        /// <remarks/>
        RUC,
        
        /// <remarks/>
        CARNET_EXTRANJERIA,
        
        /// <remarks/>
        PASAPORTE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.stockify.pucp.edu.pe/")]
    public enum tipoEmpresa
    {
        
        /// <remarks/>
        CLIENTE,
        
        /// <remarks/>
        PROVEEDOR,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpresas", WrapperNamespace="http://services.stockify.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpresasRequest
    {
        
        public listarEmpresasRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpresasResponse", WrapperNamespace="http://services.stockify.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpresasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.stockify.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StockifyWeb.EmpresaWS.empresa[] @return;
        
        public listarEmpresasResponse()
        {
        }
        
        public listarEmpresasResponse(StockifyWeb.EmpresaWS.empresa[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEmpresa", WrapperNamespace="http://services.stockify.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerEmpresaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.stockify.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerEmpresaRequest()
        {
        }
        
        public obtenerEmpresaRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEmpresaResponse", WrapperNamespace="http://services.stockify.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerEmpresaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.stockify.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StockifyWeb.EmpresaWS.empresa @return;
        
        public obtenerEmpresaResponse()
        {
        }
        
        public obtenerEmpresaResponse(StockifyWeb.EmpresaWS.empresa @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.stockify.pucp.edu.pe/")]
    public enum estado
    {
        
        /// <remarks/>
        NUEVO,
        
        /// <remarks/>
        MODIFICADO,
        
        /// <remarks/>
        ELIMINADO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarEmpresa", WrapperNamespace="http://services.stockify.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarEmpresaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.stockify.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StockifyWeb.EmpresaWS.empresa empresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.stockify.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StockifyWeb.EmpresaWS.estado estado;
        
        public guardarEmpresaRequest()
        {
        }
        
        public guardarEmpresaRequest(StockifyWeb.EmpresaWS.empresa empresa, StockifyWeb.EmpresaWS.estado estado)
        {
            this.empresa = empresa;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarEmpresaResponse", WrapperNamespace="http://services.stockify.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarEmpresaResponse
    {
        
        public guardarEmpresaResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEmpresa", WrapperNamespace="http://services.stockify.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarEmpresaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.stockify.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarEmpresaRequest()
        {
        }
        
        public eliminarEmpresaRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEmpresaResponse", WrapperNamespace="http://services.stockify.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarEmpresaResponse
    {
        
        public eliminarEmpresaResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface EmpresaWSChannel : StockifyWeb.EmpresaWS.EmpresaWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class EmpresaWSClient : System.ServiceModel.ClientBase<StockifyWeb.EmpresaWS.EmpresaWS>, StockifyWeb.EmpresaWS.EmpresaWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EmpresaWSClient() : 
                base(EmpresaWSClient.GetDefaultBinding(), EmpresaWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.EmpresaWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmpresaWSClient(EndpointConfiguration endpointConfiguration) : 
                base(EmpresaWSClient.GetBindingForEndpoint(endpointConfiguration), EmpresaWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmpresaWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EmpresaWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmpresaWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EmpresaWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmpresaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StockifyWeb.EmpresaWS.listarEmpresasResponse> StockifyWeb.EmpresaWS.EmpresaWS.listarEmpresasAsync(StockifyWeb.EmpresaWS.listarEmpresasRequest request)
        {
            return base.Channel.listarEmpresasAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockifyWeb.EmpresaWS.listarEmpresasResponse> listarEmpresasAsync()
        {
            StockifyWeb.EmpresaWS.listarEmpresasRequest inValue = new StockifyWeb.EmpresaWS.listarEmpresasRequest();
            return ((StockifyWeb.EmpresaWS.EmpresaWS)(this)).listarEmpresasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StockifyWeb.EmpresaWS.obtenerEmpresaResponse> StockifyWeb.EmpresaWS.EmpresaWS.obtenerEmpresaAsync(StockifyWeb.EmpresaWS.obtenerEmpresaRequest request)
        {
            return base.Channel.obtenerEmpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockifyWeb.EmpresaWS.obtenerEmpresaResponse> obtenerEmpresaAsync(int id)
        {
            StockifyWeb.EmpresaWS.obtenerEmpresaRequest inValue = new StockifyWeb.EmpresaWS.obtenerEmpresaRequest();
            inValue.id = id;
            return ((StockifyWeb.EmpresaWS.EmpresaWS)(this)).obtenerEmpresaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StockifyWeb.EmpresaWS.guardarEmpresaResponse> StockifyWeb.EmpresaWS.EmpresaWS.guardarEmpresaAsync(StockifyWeb.EmpresaWS.guardarEmpresaRequest request)
        {
            return base.Channel.guardarEmpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockifyWeb.EmpresaWS.guardarEmpresaResponse> guardarEmpresaAsync(StockifyWeb.EmpresaWS.empresa empresa, StockifyWeb.EmpresaWS.estado estado)
        {
            StockifyWeb.EmpresaWS.guardarEmpresaRequest inValue = new StockifyWeb.EmpresaWS.guardarEmpresaRequest();
            inValue.empresa = empresa;
            inValue.estado = estado;
            return ((StockifyWeb.EmpresaWS.EmpresaWS)(this)).guardarEmpresaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StockifyWeb.EmpresaWS.eliminarEmpresaResponse> StockifyWeb.EmpresaWS.EmpresaWS.eliminarEmpresaAsync(StockifyWeb.EmpresaWS.eliminarEmpresaRequest request)
        {
            return base.Channel.eliminarEmpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockifyWeb.EmpresaWS.eliminarEmpresaResponse> eliminarEmpresaAsync(int id)
        {
            StockifyWeb.EmpresaWS.eliminarEmpresaRequest inValue = new StockifyWeb.EmpresaWS.eliminarEmpresaRequest();
            inValue.id = id;
            return ((StockifyWeb.EmpresaWS.EmpresaWS)(this)).eliminarEmpresaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EmpresaWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EmpresaWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://oscar-acernitro:8080/StockifyWS-1.0-SNAPSHOT/EmpresaWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EmpresaWSClient.GetBindingForEndpoint(EndpointConfiguration.EmpresaWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EmpresaWSClient.GetEndpointAddress(EndpointConfiguration.EmpresaWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            EmpresaWSPort,
        }
    }
}
